export const LOADING_PASSWORDS = 'LOADING_PASSWORD'
export const SUCCESS_LOAD_PASSWORDS = 'SUCCESS_LOAD_PASSWORDS'
export const ERROR_LOAD_PASSWORDS = 'ERROR_LOAD_PASSWRODS'

export const ADD_PASSWORD = 'ADD_PASSWORD'
export const DELETE_PASSWORD = 'DELETE_PASSWORD'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'