export const LOADING_USER = 'LOADING_PASSWORD'
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_PASSWORDS'
export const ERROR_LOAD_USER= 'ERROR_LOAD_PASSWRODS'

export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'